### ISSUE TITLE
Rabbot Support

### ISSUE THREAD

**Issue by benjsicam** [derickbailey/rabbus#25]
Any plans on supporting the new library? https://www.npmjs.com/package/rabbot

**Comment by mxriverlynn** [comment]
i started work on that a while back, but my current project w/ my client has not needed rabbitmq, so i haven't been able to complete the transition yet. it's a pretty high priority for me, though. there's a lot of features and fixes in rabbot that make it worth the effort to change.

**Comment by rhyslbw** [comment]
Doesn't seem to be a breaking change with the fundamental API, so should just work as a drop-in replacement. Good thing the driver abstraction isn't a dependency 👍 

@derickbailey Maybe you could curate some issues that are now achievable with rabbot, and create new ones for upgrades not yet reported.

**Comment by mxriverlynn** [comment]
yeah, i need to get on this soon. 

i'm ramping up for my client work that heavily uses rabbus again, so i'm hoping that i'll be making time to get the PRs and issues handled, including this one (which is top priority, IMO)

**Comment by mxriverlynn** [comment]
restarted work on this, and the update is looking good now. i've got a branch at https://github.com/derickbailey/rabbus/tree/rabbot if you want to give it a whirl.

it will be another week or so before i have time to really put this branch through it's paces with my major projects, but any feedback on whether or not it works for anyone else would be greatly appreciated and help move things forward!

**Comment by rhyslbw** [comment]
If you open a PR as a WIP the feedback can be left inline

**Comment by mxriverlynn** [comment]
good idea @rhyslbw - i'm going to close this issue and we can continue the discussion on #26
