### ISSUE TITLE
Passed the `response` on `reply` event.

### ISSUE THREAD

**Issue by rtorino** [derickbailey/rabbus#3]
How about passing the response object on `reply` event in the responder? We have a use case where we have a logger-service that logs every responder response. It would be easier if we could just listen for `reply` event on every responder instance and grab the `response` data that it passed and send it to the logger-service.

**Comment by mxriverlynn** [comment]
I'm not sure I understand the request. Can you elaborate with code sample of what you would like to be able to do?

**Comment by rtorino** [comment]
@derickbailey our use case is to send every response to a logger-service. In this line https://github.com/derickbailey/rabbus/blob/master/rabbus/lib/responder.js#L90 where reply event is emitted, it could be useful if we could pass the response object like `that.emit("reply", response);`

**Comment by mxriverlynn** [comment]
this is done in the dev branch. hoping for a release soon.
