### ISSUE TITLE
Expose Additional Queue Options

### ISSUE THREAD

**Issue by esatterwhite** [derickbailey/rabbus#5]
Currently, the `receiver`, `responder` and `subscriber` all pass a hard coded object to the [addQueue](https://github.com/LeanKit-Labs/wascally#addqueue-queuename-options-connectionname-) method to wascally. It would be beneficial to all additional options to be added and passed in. In particular, `messageTtl`, `expires`, and `deadLetter`.

**Comment by mxriverlynn** [comment]
hey @esatterwhite 

sorry this took me so long to address! been crazy busy... but I'm finally on it, and the dev branch is showing the new direction of things. https://github.com/derickbailey/rabbus/tree/dev

the new configuration setup will allow you to pass any parameter you want, through to wascally. you won't be limited by what rabbus supports anymore. instead, rabbus provides it's own set of defaults but allows you to override them and provide any other options you want.

if you have some time to try out the dev branch, i would love to get some feedback on whether or not this is working.

**Comment by mxriverlynn** [comment]
v0.4.x has this feature in it now
